
## ------------------------------------- ##
##    Trackers configuration list        ##
## ------------------------------------- ##

tracker:

  # - Plark Service -
  #
  # Bitcoin
  # Use service https://btc.insight.plark.io
  BTC:
    type:       insight
    apiUrl:     https://btc.insight.plark.io/api
    webSocket:  wss://btc.insight.plark.io


  # - Plark Service -
  #
  # Litecoin
  # Use service https://ltc.insight.plark.io
  LTC:
    type:       insight
    apiUrl:     https://ltc.insight.plark.io/api
    webSocket:  wss://ltc.insight.plark.io


  # DashCoin
  # Use service https://insight.dash.org
  DASH:
    type:       insight
    apiUrl:     https://insight.dash.org/insight-api-dash
    webSocket:  wss://insight.dash.org


  # Ethereum
  # Use service https://infura.io
  ETH:
    type:       infura
    apiUrl:     https://api.infura.io/v1/jsonrpc/mainnet




  # - Plark Service -
  #
  # Bitcoin Test
  # Use service https://btct.insight.plark.io
  BTCt:
    type:       insight
    apiUrl:     https://btct.insight.plark.io/api
    webSocket:  wss://btct.insight.plark.io


  # - Plark Service -
  #
  # Litecoin Test
  # Use service https://ltct.insight.plark.io
  LTCt:
    type:       insight
    apiUrl:     https://ltct.insight.plark.io/api
    webSocket:  wss://ltct.insight.plark.io


  # DashCoin Test
  # Use service https://testnet-insight.dashevo.org
  DASHt:
    type:       insight
    apiUrl:     https://testnet-insight.dashevo.org/insight-api-dash
    webSocket:  https://testnet-insight.dashevo.org


  # Ethereum Ropsten Test
  # Use service https://infura.io
  ETHt:
    type:       infura
    apiUrl:     https://api.infura.io/v1/jsonrpc/ropsten
